from typing import List, Tuple
from Models import Income, Expense

class IFilterService:
    @property
    def income_month(self) -> int: ...

    @property
    def income_year(self) -> int: ...

    @property
    def expense_month(self) -> int: ...

    @property
    def expense_year(self) -> int: ...

    def change_income_month(self, delta: int) -> Tuple[int, int]: ...
    def change_expense_month(self, delta: int) -> Tuple[int, int]: ...

    def filter_incomes(self, incomes: List[Income]) -> List[Income]: ...
    def filter_expenses(self, expenses: List[Expense]) -> List[Expense]: ...

    def get_income_month_label(self) -> str: ...
    def get_expense_month_label(self) -> str: ...