# Services/IFinanceService.py
from typing import Protocol, List, Optional
from datetime import datetime
from Models import Expense, Income, Obligation
from Models.enums import ExpenseType, IncomeType, ObligationType

class IFinanceService(Protocol):
    """Интерфейс FinanceService"""

    # READ
    def get_expense(self) -> List[Expense]: ...
    def get_income(self) -> List[Income]: ...
    def get_obligation(self) -> List[Obligation]: ...
    def get_expense_by_id(self, expense_id: int) -> Optional[Expense]: ...
    def get_income_by_id(self, income_id: int) -> Optional[Income]: ...
    def get_obligation_by_id(self, obligation_id: int) -> Optional[Obligation]: ...
    def get_expenses_by_period(self, start: datetime, end: datetime) -> List[Expense]: ...
    def get_incomes_by_period(self, start: datetime, end: datetime) -> List[Income]: ...

    # CALCULATE
    def calculate_balance(self) -> float: ...

    # CREATE
    def add_expense(self, amount: float, expense_type: ExpenseType, description: str, date: Optional[datetime]) -> None: ...
    def add_income(self, amount: float, income_type: IncomeType, description: str, date: Optional[datetime]) -> None: ...
    def add_obligation(self, name: str, obligation_type: ObligationType, amount: float,
                       due_date: Optional[datetime] = None, start_date: Optional[datetime] = None,
                       monthly_payment: float = 0.0, paid_amount: float = 0.0,
                       description: str = "") -> None: ...

    # UPDATE
    def update_expense(self, expense: Expense) -> None: ...
    def update_income(self, income: Income) -> None: ...
    def update_obligation(self, obligation: Obligation) -> None: ...

    # DELETE
    def delete_expense(self, expense_id: int) -> None: ...
    def delete_income(self, income_id: int) -> None: ...
    def delete_obligation(self, obligation_id: int) -> None: ...